# Generated by Django 4.0.2 on 2022-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
                ('fund', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('agm_date', models.DateField()),
                ('agm_record', models.DateField()),
            ],
        ),
    ]
