# Generated by Django 4.0.2 on 2022-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_position_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='shares_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='shares_outstanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='treasury_shares',
            field=models.IntegerField(default=0),
        ),
    ]
