# Generated by Django 4.0.2 on 2022-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_position_shares_issued_position_shares_outstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='shares_issued',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='shares_outstanding',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='treasury_shares',
            field=models.BigIntegerField(default=0),
        ),
    ]
